apiVersion: v1
kind: ConfigMap
metadata:
  name: wiremock-config
data:
  service.json: |
    {
      "request": {
        "method": "GET",
        "url": "/hello"
      },
      "response": {
        "status": 200,
        "jsonBody": {"message":"Hello World!"},
        "headers": {
            "Content-Type": "application/json"
        }
      }
    }

  status.json: |
    {
      "request": {
        "method": "GET",
        "url": "/status"
      },
      "response": {
        "status": 200,
        "jsonBody": {"message":"All up and running"},
        "headers": {
            "Content-Type": "application/json"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock-deployment
spec:
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
    spec:
      containers:
        - name: wiremock
          image: rodolpheche/wiremock
          resources:
            limits:
              memory: "128Mi"
              cpu: "256m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: wiremock-config-volume
              mountPath: /home/wiremock/mappings
      volumes:
        - name: wiremock-config-volume
          configMap:
            name: wiremock-config
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock-service
spec:
  type: ClusterIP
  selector:
    app: wiremock
  ports:
    - port: 80
      targetPort: 8080
