version: '3.3'
services:
  service1:
    image: rodolpheche/wiremock
    ports:
      - '9001:8080'
    volumes:
      - ../proxy/apis:/home/wiremock/mappings
  echo1:
    image: inanimate/echo-server
    ports:
      - '9002:8080'
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
